export const SETTING_STATUS = {
  POLYGON_EDIT: "POLYGON_EDIT",
  POLYGON_CREATE: "POLYGON_CREATE",
  POLYGON_SELECTING: "POLYGON_SELECTING",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_EDIT: "CATEGORY_EDIT",
  CATEGORY_REMOVE_APPROVAL: "CATEGORY_REMOVE_APPROVAL",
  NONE: "NONE",
};
